### ISSUE TITLE
[Question] Reverting the themes

### ISSUE THREAD

**Issue by TheFlash787** [TheFonix/Pterodactyl-Themes#1]
Hey! Is there a script I can use to revert the theme that was added?

Thanks!

**Comment by ghost** [comment]
I'd really want to know that too :+1:

**Comment by Plexiate** [comment]
All that's happening in this is:
`    cp -r Pterodactyl-7/Graphite/public ..
    cp -r Pterodactyl-7/Graphite/resources ..`
Just grab fresh files from https://github.com/pterodactyl/panel
