### ISSUE TITLE
Needs updating to latest version of Pterodactyl

### ISSUE THREAD

**Issue by AshiePleb** [TheFonix/Pterodactyl-Themes#12]
Hey is there any chance you could update these themes to the latest version of Pterodactyl as it causes errors when trying to use the themes with latest version of Pterodactyl

**Comment by usefulLynx65084** [comment]
+1

**Comment by TheFonix** [comment]
Will get it all moved over asap. Thanks for the heads up

**Comment by Artuto** [comment]
Can confirm, its due this error http://bin.ptdl.co/nqcen

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
+1 - Thx for the great work!

**Comment by TheFonix** [comment]
This Repo has now been updated to support panel 0.7.15
