### ISSUE TITLE
don't overwrite default theme

### ISSUE THREAD

**Issue by untuned** [TheFonix/Pterodactyl-Themes#13]
https://pterodactyl.io/community/tutorials/custom_theme_setup.html

**Comment by TheFonix** [comment]
I’m aware of this document?

**Comment by mkcoldwolf** [comment]
> I’m aware of this document?

But then why overwrite the default theme? XD
i remeber when i first using this project , it does overrwrite the default theme
and backup once for default theme
it doesn't really good if user dont know how to restore the backup
so... i think follow the document is better

**Comment by TheFonix** [comment]
I currently dont have enough hours in a day to re-create all the implementation, in the nicest way, you could just download the files and install it yourself if it bothers you that much :) Maybe when i have a free while i will change it to use Pterodactyls themeing system. But until then... this works... if somebody doesn't know how to unzip a zip file then google will be their best friend! :)
