### ISSUE TITLE
Possibility of changing the colour scheme on Minecraft Madness?

### ISSUE THREAD

**Issue by Osprey4444** [TheFonix/Pterodactyl-Themes#15]
I was just wondering if it were possible to change the dark colour scheme of 'Minecraft Madness (Panel 0.7.15)' to a White theme instead? such as the Navigation Bar, Server & Node List, Console, File Manager etc? I would do this myself, but I have no clue how to, im sorry if this is a bother.

**Comment by larsjarred9** [comment]
This can be done by changing the colors in the CSS source code
