### ISSUE TITLE
Default Theme

### ISSUE THREAD

**Issue by AlexanderOFGR** [TheFonix/Pterodactyl-Themes#17]
Hello, I know this may sound stupid, but I believe it's easy to create since the default theme is offered in the [Pterodactyl's GitHub page](https://github.com/pterodactyl/panel/tree/develop/public/themes/). I think it would be a great idea to include the Default Pterodactyl Panel Theme in your Themes Repository. **That way, if a person wants to go back to the default theme it's easier for him.** 

**_Thanks, AlexanderOF_**

**Comment by TheFonix** [comment]
They can just get it from the pterodactyl repository though? @AlexanderOFGR

**Comment by AlexanderOFGR** [comment]
I know, but it's a bit tricky if you want to go back to the original theme. At least that's my opinion...
