### ISSUE TITLE
Update to Panel version v0.7.16

### ISSUE THREAD

**Issue by Liyf4TakingLs** [TheFonix/Pterodactyl-Themes#18]
I see that its working normal on v0.7.16 , but only issue found so far is that disk space isnt shown.
![image](https://user-images.githubusercontent.com/43788244/71779807-1ae72580-2fba-11ea-9c6c-18c88283fb0f.png)
Thanks!
Regards ,
- Liyf4TakingLs

**Comment by joshuasing** [comment]
Please update. Thanks.

**Comment by stijnb1234** [comment]
An update will be nice. Thanks

**Comment by Artuto** [comment]
Bump

**Comment by Liyf4TakingLs** [comment]
I have fixed this by my self :) Just go and add few lines from last version and it should work...
![image](https://user-images.githubusercontent.com/43788244/74561135-50dbda00-4f68-11ea-88c8-d9d5363a063b.png)

**Comment by Artuto** [comment]
> I have fixed this by my self :) Just go and add few lines from last version and it should work...
> ![image](https://user-images.githubusercontent.com/43788244/74561135-50dbda00-4f68-11ea-88c8-d9d5363a063b.png)

You should share it for us who are waiting

**Comment by TheFonix** [comment]
Is that the only Element of the new panel update that causes issues? for the themes?

**Comment by Liyf4TakingLs** [comment]
Thats not the only issue :
Under Admin Mode > Nodes > YourNode > Servers - There are the following issues :
- Status is under Relation
- Status is empty
- Disk usage is in cpu usage display
- Cpu % is in disk usage
Thats All What I found!
![image](https://user-images.githubusercontent.com/43788244/74684133-64d34600-51cb-11ea-9233-e56268e16c14.png)

**Comment by Liyf4TakingLs** [comment]
You can contact me on discord so I can maybe help If you need help fixing the issues. 
! ! Liyf4TakingLs#0630

**Comment by TheFonix** [comment]
The problem is that you have an old Resources Folder... my theme no longer replaces the Resources folder... ill build a single liner for you guys to run in the panel directory so it sorts all your resources out, this should solve your issues :)

**Comment by TheFonix** [comment]
Like i said ive made a command to re-build your resources library from the new version of Pterodactyl, this should sort all the issues out... 

`curl https://i.hardcastle.xyz/fixer.sh | sh` (This needs to be ran inside your panel directory)

Let me know if this fixes it for you guys
