### ISSUE TITLE
Black & White Theme Blue Boxes

### ISSUE THREAD

**Issue by alexanderofyt** [TheFonix/Pterodactyl-Themes#19]
![pterodactylblacktheme](https://user-images.githubusercontent.com/64520410/80568326-7a50c180-89ff-11ea-900b-6a78029cdebc.PNG)

Hello! Thanks for providing free themes for everyone to use! 
I found a problem with the Black and White theme, the boxes in the picture above are not black. Not quite sure if this is a bug with the install or not. **Thank you!**

**Comment by TheFonix** [comment]
This will be sorted when i re-released the themes for the latest version of the panel. Thanks
