### ISSUE TITLE
<code> tags showing up in text

### ISSUE THREAD

**Issue by RainyRainer** [TheFonix/Pterodactyl-Themes#2]
In user settings at the bottom of the update identity settings the text about allowed characters in usernames has visible code tags for some reason.

Screenshot:
https://i.gyazo.com/f515872246a580096cd2d8c73fa52138.png

**Comment by RainyRainer** [comment]
Theme that I'm using is Graphite.

**Comment by TheFonix** [comment]
Thank you! Will sort that out on the new release of themes.
