### ISSUE TITLE
just pointing out that v0.7.17 is no longer latest

### ISSUE THREAD

**Issue by TekExplorer** [TheFonix/Pterodactyl-Themes#22]
its v0.7.18 now. mainly to edit the readme

**Comment by TheFonix** [comment]
This Repo doesn't work with 0.7.18 Hence why no Readme update.

**Comment by TekExplorer** [comment]
Really? I thought it was just a security update; no theming changes and such.

**Comment by TekExplorer** [comment]
somehow i dont believe that and im offended now.

**Comment by azeoix** [comment]
https://i.imgur.com/cKqRWf9.png Explain?
