### ISSUE TITLE
[Question] Are themes Panel v1.0 compatible

### ISSUE THREAD

**Issue by ROMVoid95** [TheFonix/Pterodactyl-Themes#26]
I was going to post this question in the previous issue. But figured it would be better to have its own report.

Are the themes compatible on the v1.0+ of the panel?

**Comment by poppin-fresh** [comment]
I'd also love to see them updated, especially the MC theme if possible. great work.

**Comment by ROMVoid95** [comment]
I can verify they are compatible, but for reference: They do not change the new server view, only the views from the pre-1.0 panels.
